let kanji_meaning =[
"one (line radical)", "two", "three", "total", "child", "woman", "like", "rape", "mouth (small box radical)", 
"products", "say", "below", "un", "no", "ten", "old", "dream come true", "measure", "heel", "seven", "compare", 
"scold", "sun, day", "the gist", "insect", "chant", "crystal", "former", "early", "danna (husband)", "white", 
"everyone", "water", "spring", "ice", "forever", "swim", "stay for the night", "juice, soup", "mix", "moon (organ)", 
"big lake", "bright", "animal fat", "gall bladder / daring", "morning", "fire", "flame", "faint", "consult", "nail", 
"streetlight", "possible", "stream", "revise", "rice field", "neighborhood, small town", "cultivated field", "stomach", 
"put/go in", "person", "what?!?", "believe", "transform", "flower", "suffer", "grass", "luggage", "George Michael's Moustache", 
"the inside", "meat", "yen/circle", "small city (dagger radical)", "lung", "older sister", "eye", "dare", "hat", "my own", 
"beret", "restaurant", "bring to a halt", "graduate", "direction / method / person", "10000", "formal visit", "prevent", 
"fatty food", "again (crotch radical)", "pair", "servant / dood", "culture/ sentence", "unison", "economy / to be over", 
"numeral4", "get", "shout", "heart", "surely", "get mad", "son / breath", "think", "loser", "dying", "busy", "forget", 
"blind, ignorant", "without reason or permission", "net", "neglect/ egotistic", "manga", "sub-", "bad", "evening", 
"many", "dream", "late night", "liquid", "name, famous", "death", "katakana toe", "outside", "above", "dinner table", 
"fortune teller/ occupy", "point", "crown", "residence", "cheap / safe", "letter", "announce", "fight or quarrel", "eight", 
"hole", "six", "run parallel to", "moocow", "public", "lawsuit", "big thing counter", "cure", "begin", "lazy", "talent", "bear", 
"looks like", "Buddha", "standing worms", "stand up", "spicy / painful", "luck, happiness", "manager", "cry", "rank", "sound", 
"emblem / chapter", "dark", "meaning", "a hundred million", "recollect", "gate", "pitch-black darkness", "a period of time", 
"question, problem", "sword", "before", "cut / important", "summon", "shining / Showa era", "contrast", "understand / divide / minute",
"type of medicine", "punishment", "blade", "hide / endure", "admit", "strong", "add", "cooperate", "threaten", "make an effort", "man",
"the number 9", "research", "round", "get good at", "to hella do", "small size", "a little (amount)", "inferiority", "odd", 
"ministry / cut down on", "capital", "cool place", "scene", "show (altar radical)", "religion", "lonely", "supervisor", "Eazy", 
"childhood", "deep profound", "raising of domestic animals", "store or put aside", "string", "acquaint", "line", "cotton", "slender", 
"general / total", "look up", "to supply", "ambiguous", "silk", "group, tribe", "grandchild", "be involved with", "dry out", "edition", 
"utilize", "liver", "potato", "sweat", "cosmos", "thousand", "tongue", "conversation", "vivid, lively", "quit", "break at work", "half",
"judgement", "accompany", "equal / level", "art or literary criticism", "call to someone", "earth", "village", "quantity", "black",
"kid", "yearn for", "bury", "boy / monk", "puke", "cram school", "samurai radical", "work", "intention, volition", "good omen", 
"cram in", "bind", "magazine", "dizzy", "get old", "filial piety", "professional", "author", "together", "various", 
"government office", "hot place", "simmer/stew", "turkey", "char / scorch", "without", "upkeep", "sole or only", "who??", 
"prepare / criteria", "defend", "horse", "stop", "your Moms", "consent", "walk", "interfere", "purple", "foot/ be enough", 
"peer pressure", "tread on", "correct", "fer shure", "plan", "proof", "distort", "run", "exceed/ go over", "R for ROCK", 
"train station", "noon", "reason / translation", "swamp / bling", "hand", "select", "infer", "depict", "submit a proposal", 
"pay", "call bullshit on", "finger / point at", "pound", "beckon", "kidnap", "carry on your back", "directly contact", "clap", 
"insert", "observe/guard", "ear", "take", "most", "photo-shoot", "hobby", "disgrace", "listen/ ask", "axe", "fold", "hill", 
"philosophy", "vow", "accuse", "bamboo", "muscle", "simplicity", "key", "make", "yesterday", "motion", "near", 
"around here/around that time", "press upon", "get crowded", "plural/delivery", "progress", "refer to", "tree", "grove", "forest", 
"book / the real", "body", "rest", "boundary / limit", "analyze", "take measures", "stab / business card", "new", "collect", "shelf", 
"pine", "wither", "partner", "box", "idea/imagination", "prohibition", "fruit / result", "section or lesson", "sweets/pastry", "east",
"practice", "guide/proposal", "one cup of liquid", "knee or lap", "guarantee/maintain ", "spin", "manipulate/ chastity", "dye",
"miscellaneous , random", "wheat", "childish", "peace/ Japan", "secret", "me / private", "one second", "transfer", "handy", 
"season", "member", "good smell", "fall", "sorrow", "the tip", "not yet", "little sister", "flavor", "rice / America", "perplexed",
"mystery", "decision/judgement/refuse", "succeed / inherit", "be sticky", "essence", "grain", "powder", "come/future", "number", 
"judge", "big", "waaay in the back", "strange", "get close", "stinky odor", "get worked up", "instrument", "thrust", "central", 
"project, reflect", "heroic", "dog", "lay face down", "shut up", "nature", "burn", "fat", "bad quality", "from China (radical)",
"Chinese", "difficult", "be employed at", "lament, sigh", "opium", "model", "grave", "make a living", "recruit", "curtain", 
"desert", "big box", "origin", "kindness", "bacteria", "trouble", "prisoner", "rotate / times", "hard", "individual", "well", 
"surround", "beef bowl", "king", "ball", "country", "treasure", "reason", "have responsibility for", "pregnant", "emperor", "desire",
"holy", "extent", "master/mainly", "contract", "enjoy a drink and a smoke", "honorable", "pour / be careful", "pillar", "dwell", 
"stop at", "damage", "divide", "element", "constitution", "blue", "request", "pure", "spirit", "weather get good now", "emotion", 
"rifle", "life / birth", "star", "sex / essential nature", "family name", "vermilion", "share, stock", "play around", "symmetry", 
"second rank / girl", "dessicate", "your Moms", "poison/ addict", "every", "plum", "ocean", "regret", "despise", "middle", "loyalty", 
"medical patient", "friendship", "insizzect", "snake", "mosquito", "make noise", "corpse", "genus/affiliation", "live", "nun", "mud", 
"urine", "butt", "print", "door", "area / attribute", "shoulder", "hire", "wife/cluster", "return", "teardrop", "fur", "tail", "bunny ears", 
"leather/revolution", "shoe", "sweet", "a certain", "plot", "human legs", "look", "leniency", "roast / grill", "border", "reality", 
"parents/kindness", "older brother", "overcome", "condition", "contest", "baby", "animal legs", "shellfish (money)", "buy", 
"get indignant", "spew", "cargo", "poverty", "save up", "bet or stake", "quality", "rent money", "chastity", "detective", "clerk", 
"harm", "rule", "side of something", "scientific measurement", "pierce", "adapt", "condemn", "achievements", "pile up", "exalted", 
"bequeath", "soldier", "beach", "fishhook", "lose", "fish", "horn/corner", "touch", "pi", "nice thick pie", "sell", "continue", "read", 
"window", "look for", "deep", "tool", "original", "complete", "west", "ballot", "sign, mark", "drift", "liquor", "drunk", "value", 
"important", "waist", "smoky", "skill / age", "loot", "raw materials", "close store", "husband", "agree", "substitute", "lurk", 
"criteria", "pinch", "t.c.f.b.b.y.e.s.i.y.l.", "habitat", "shining", "merely", "sakura", "carrot", "whittle down", "erase", "nest", 
"vegetable", "float", "receive", "compromise", "instruct", "gather", "been a long time", "each", "love", "customer", "fall,drop", 
"character, aspect", "get entangled", "abbreviation", "road", "clause", "barley", "sour", "grasping hand", "excel", "invite / entice", 
"transparent", "carry in hand", "reach / amount to", "suck", "level", "treatment", "snout", "tranquil", "perpetrate", "immerse", "green", 
"urgent", "hit the target", "swordswallower", "housewife / lady", "sweep", "go back home", "foreign emperor", "tighten", "MUTANT", "jump",
"rinse", "day of the week", "craft or industry", "air", "abstain", "dark lipstick red color", "success", "pirate's hook", "adroit", 
"bestow", "copy", "dirty", "extreme", "be proud of", "ID number", "consider", "torture", "ritual", "wipe", "attempt to do", "military", 
"generation / instead of", "lend", "spear", "clique", "be misguided or tempted", "we", "bandit", "region", "fight", "cultivate", 
"how much?", "machine", "sentry", "employment", "organization / weave", "be conscious", "container", "ward", "gallop", "giant super huge", 
"repel", "distance", "vassal", "solid, steadfast", "tense", "clever", "view", "to confront", "princess", "small animal", "artisan", 
"the numeral 4", "exclaim", "exchange", "lack", "Europe", "sing", "blow", "cook rice", "director", "integer, to count", 
"counter for flat objects", "agile / sensitive", "be defeated", "breakdown, accident", "politics", "release", "teach", "intense", 
"multiple, many", "attack", "Yosemite Sam", "enemy", "suitable", "drip", "pluck", "myself", "renew / improve", "wake up / occur", 
"century", "diary", "distribute", "demand/ask", "rescue", "sphere", "cliff", "strict", "diligence", "chronicle", "thick", "pressure", 
"makeup", "furnish", "ash/ gray", "childbirth, production of things", "original/ high plain", "hot spring / origin", "anti", 
"return or respond", "slope", "plank", "provisional", "transaction", "open scissors", "become", "sincerity", "go beyond", 
"traditional storehouse", "internal organ", "years old", "annihilate", "terrible majesty", "castle", "illusion", "mood", "decide", 
"pleasant", "Hitler", "beast", "decrease", "feeling", "regrettable", "same", "cylinder /pipe", "administer", "formal visit  / question", 
"part of speech", "hitchhiker", "trip", "faction/bling", "vein", "far away", "far", "public park", "environment", "kick in the nuts", 
"express", "cloth", "depend on", "sack", "trial", "praise", "backside", "pitiful", "decline,wane", "good", "daughter", "retreat", 
"wavelike", "eyeball", "hold a grudge", "root", "town", "limit", "one's hometown", "echo", "story of a building", "impede", 
"institution", "ward off", "entrapped", "major city", "hide", "double the amount", "section", "dissect", "double", 
"guy so macho he has two dicks", "epic!!!", "dress up", "circumstance", "go to bed", "north", "stature / back of the body", "hurl", 
"system", "mass production", "inform", "produce", "horrendous", "earlier/ the tip", "wash", "terrorist", "front surface / face", 
"hundred", "grieve", "kindhearted/excel", "lodge at", "contract / shrink", "rock", "sand", "pulverize", "foundation", "mountain", 
"boulder", "belt", "delay / be overdue", "sponsor", "collapse", "hard to see", "occult", "shore", "carbon", "mount", "bird", "island", 
"animal cry", "bean", "rejoice", "stoked", "head", "summer", "beseech", "stubborn", "around that time", "summit/climax", 
"amount of money / forehead", "category,type", "topic", "look back on", "lean", "item/paragraph", "river", "sequence", "state", 
"kunyomi", "go wild / rough", "be in a rush / freaked out", "horny", "neck", "street", "tax", "explain", "get naked", "magnet", 
"sheep", "yen", "south", "beauty", "fresh", "expert", "Pacific Ocean / the West", "slow / late", "wear / arrive", "cultivate, rear", 
"righteousness", "politeness", "discussion", "important person", "heaven", "append", "laugh", "chug", "horny heaven", "send", "bloom", 
"connected to", "roll up", "range / area of influence", "certificate, cupon", "win", "bow", "younger brother", "rank or number in series", 
"boil water", "expenses", "burly", "pull", "bullet / play guitar / bounce", "red", "bay", "vestiges", "passion", "change", "long / boss", 
"stretch", "notebook", "peaked roof", "risk", "steep / risky", "investigate", "thrifty", "saber", "test", "gold", "sharp", "rust", 
"record", "mirror", "shut/chain", "silver", "needle", "bronze", "tea", "umbrella", "all", "scheme", "eat", "drink", "decorate", 
"rice / meal", "keep a pet", "trunk", "stable", "throw away", "excess", "paint", "on the way", "exclude", "storage", "originate / creative", 
"introduce / intervene", "the world", "to suit", "provide", "tower", "pick up off the ground", "board", "answer", "rambo", "now", 
"include", "concern", "command", "tiny electric bell or buzzer", "territory", "life", "chill", "cold thing", "to freeze", 
"exhaust, use up", "winter", "end", "next", "someone's shape, body, form", "capital (as in $$$)", "three Stooges", "cold", 
"musical performance", "spring /sexy", "pole", "truth", "counter for books", "flat", "knit", "deceive", "be inclined", "bookstore", 
"make a case for", "principles", "glue", "stick to", "attachment", "attack/discuss", "steal by force", "protect", "group", "ticket", 
"hicktown", "lifespan/sushi", "console", "ask", "lead", "struggle", "temple", "poem", "time", "hold", "samurai kanji", 
"equal /etc./plural", "esteem", "rumor", "dad", "combine", "against", "school", "suburb", "effective", "wring out / strangle", 
"TNT plunger", "specialty", "museum /extensive", "tie up", "weak or thin", "performance", "do a favor", "lay out / site", "pit", 
"a drawing", "both", "full", "pull out / hand over", "yield, get out of the way", "dig", "can, like 'canned beef'", "sway, joggle", 
"society", "leaf", "speak", "tooth", "chew, bite", "stage of life", "terrible", "brain", "worry", 
"divorce / physical distance between things", "arrow", "doubt", "sham", "short / brief", "doctor", "family", "climate/candidate", 
"know", "miss out on", "iron", "swan", "point of view", "recommend", "rights", "make certain", "car", "heavy / overlap", "drip, dangle", 
"ride a vehicle", "base", "ring/tire", "counter for shops", "evaluate", "soft", "appear in print", "army", "brandish", 
"take with / inform of", "carry / luck", "dazzle", "flamboyant", "sleep", "mail", "excessive", "seed / type or kind", "movement", 
"to do your job", "swell", "injustice / mistake", "older or younger colleague", "sad", "sin", "actor", "eliminate", "take a dump", 
"lightweight", "experience", "suspicious", "Naruto", "friend", "extract", "male animal or hero", "fabric", "request / uncommon", "scary", 
"right", "left", "young", "exist", "corrupt", "bribe/ provide capital to", "discriminate", "be real", "be aware of", "fragment", 
"printing plate", "crows", "warm place", "assist", "become loose / abate", "hair", "hair", "hue", "shadow", "face", 
"admit defeat / visit", "master a skill", "wretched", "bulge", "salon", "very rare", "diagnose", "cave", "corridor", "to brush", "rot",
"react", "government", "metropolitan government", "warehouse", "shop", "sit", "floor", "mah jongg / ganja", "friction", "wide", 
"to expand", "mole", "populist", "seat", "times", "pass by", "villain", "demon", "devil", "enchant", "ugly", "clump", "despicable", 
"mr.  (speculum radical)", "bottom", "paper", "low", "marriage", "resist", "folk", "sleepy", "song / turn or bend", "plentiful", 
"classic", "chance meeting、 usually with something bad ", "payback", "farming", "thick / dense", "humiliate", "pregnancy", 
"brandish / pretend", "lips", "teepee", "climb", "festival", "edge", "police", "chafe", "open", "open", "launch", "wane", "form", 
"polish, sharpen", "penalty", "type / proper way", "noon", "allow", "cow", "incident", "special", "sacrificial victim", "sacrifice", 
"solve / untie", "thing", "animal / thing", "to fall in love with", "easy", "hot water", "hoist / deep fat fry", "sun", "wound", 
"place", "bait", "color", "exemption / license", "more or less than normal", "night", "extinct", "try hard", "lorgnette", "voice", 
"obese / manure", "pig", "elephant / phenomenon", "statue / image", "rim / omen", "home", "bride", "bring home the loot", "attain", 
"troop", "go", "slowly", "pupil / follower", "diameter", "afterwards / behind", "depart", "wait", "bargain / obtain", "obey", 
"vertical", "art / technique", "collision", "teeny", "sign / indication", "decapitated cow", "grow up / be raised", "do thoroughly", 
"withdraw", "flow", "shady", "fill up", "gun", "tradition", "until", "arrive", "polite \"do\"", "knock down", "past tense", "law", 
"get afeared", "store", "room suffix", "grasp", "international trading", "absent / stopped", "twin decapited cows", "roll over", 
"transmit", "soul", "art", "big meeting", "picture", "termite mound", "shopping district", "hang / halfway done ", "lifetime", "seal in", 
"termite pie", "continent", "power", "hot thing / fever", "diaper", "joke", "human skin", "oppose", "desk", "wind / the flu / style", 
"starve", "dispose of or manage", "evidence which is the basis for a judgment", "mediocre", "architect", "dread", "throw", "throw", 
"role", "establish", "downfall", "kill", "punch", "grrrrrroin", "charge", "the fly", "shield", "circulate", "really", 
"refrain / be prudent", "prefecture", "suspend / gamble", "correct a problem / direct contact", "put down on table", "price or ranking", 
"plant", "shhh", "agricultural breeding, reproduction", "separate", "row", "tear up", "violently intense", "example", "support", "skin", 
"him", "branch", "technique", "drum", "rend", "wave", "Mama", "courage", "beforehand", "first part / preface", "deposit", "field", 
"halberd", "flexible", "perform a task", "bundle of sticks", "shun", "ask a favor", "fast", "arrange", "pass radical", "pass", "dance", 
"t-bone steak", "pattern", "sick", "sick kanji", "hurts!!!", "get tired from hard work", "diarrhea", "molester", "symptom", "go numb", 
"butcher", "cure", "pleasure", "chide / guide", "transport", "stank", "bad habit", "avoid / dodge", "wall", "small talk", 
"medical therapy", "dormitory", "coworker", "humbly say (god radical)", "lose weight", "gentleman", "search", "stretch", "turtle shell", 
"push", "freedom / reason", "abstract", "space", "oil", "extend to", "soup", "coincidence", "corner of room", "dum diddy dum dum", "rain", 
"fog", "cloud", "get cloudy", "frost", "lightning", "shake, tremble", "leak", "snow", "atmosphere", "outdoors, public", "hedgehog", 
"ghost", "become damp, moisten", "business", "me (for dudes)", "eradicate", "dragon radical", "dragon", "waterfall", "electricity", 
"me (macho version)", "turtle", "rope", "comb", "demand", "withstand", "the edge", "wrap", "wrap", "cell", "bubble", "cannon", 
"get sick of", "hug", "chest/breast", "verse of a poem", "respect", "the fuzz", "astonish", "department", "put in custody", 
"in season/ time of month", "pottery", "scent (good or bad)", "thirsty", "promise", "promise/ roughly speaking", "motivation / '-al'", 
"fishin", "average", "plate", "steal by stealth", "hot or warm thing", "oath", "heaps of!", "salt", "oversee", "expert opinion", "blood", 
"populace", "crab", "profit", "overflow", "honor", "raise / cite/ mention", "boat", "ship", "navigation", "general / overall", 
"tray / basis", "cat", "fierce", "obscene", "monkey", "hunt", "go nuts", "solitary", "hell", "prey on / get", "narrow", "fingerprint", 
"commit a crime", "stamp", "beat, smack", "egg", "disregard", "standard / the best way to do", "the honorific \"o\"", "arm / skill", 
"immediately", "season / joint", "misfortune", "dangerous", "clown posse", "suppress", "go to pick someone up", "pompous / look up to", 
"wardrobe", "clothes", "data", "Abe Lincoln's Hat", "aim at", "one's team", "hamper", "rough texture / bad quality", "inspect", 
"tatami mat", "save", "NEcrophilia", "ancestor", "peer at", "celebrate", "company", "pray", "welfare", "GOD kanji", "wine bottle", 
"good luck", "side- or vice-", "width", "get rich", "hook", "polite", "disorder", "card / label / bill", "milk", "ducky", "first time", 
"naked", "get injured", "dork!", "complicated or compound", "entrails", "return or re-do", "put on pants or shoes", 
"valley (Swamp Thing radical)", "abundant", "want", "uncouth", "appearance", "melt", "bathe", "hell", "nose", "mourn", "calculate", 
"dialect", "ascend", "admonish / commandment", "contraption", "feathers", "fly", "the next- / the following -", "learn", "weak", 
"traditional fan", "hellbunny", "scatter", "exhibit", "concessions", "long ago", "borrow", "close but no cigar", "family register", 
"yellow", "young lady", "side / arrogant", "with", "line up / ordinary", "normal", "follower", "choose", "flood", "Tha $treetz",
"harbor", "to differ", "political wing", "rampage", "explode", "again / once more", "unicycle", "chain store", "supplement", "capture", 
"drug frenzy", "set up / care about", "lecture", "subscribe", "ditch", "fuck", "descend /rainfall / get out of vehicle ", "year", "five", 
"language", "enlightenment", "orgy", "different and therefore wrong", "high-powered, prestigious", "defense", "date", 
"twinkle / tiny bit of time", "dance / flutter", "neighbor", "spice rack", "ingredients / fees", "science", "diagram/ map", "diagonal", 
"skipping legs", "history", "all over again", "hard like a rock", "use", "convenient / poop", "(one's own) flesh", "shoot", "apologize", 
"to be in trouble", "scorpion", "area", "pond", "other", "put into practice / charity", "gain", "increase", "give", "detest", 
"buddhist monk", "layer", "washtub", "bureaucracy", "palace", "federal", "big hall", "coffin", "follow", "apply", "tube", 
"master, teacher", "mohawk", "manage (a business)", "labor", "glory", "knowledge", "bear in mind", "political party", "all the more", 
"prize", "compensate for", "usual", "assembly hall", "morally good", "mend", "goatee", "circumference", "check out", "week", "carve", 
"tall", "luxurious", "turn to face", "merchandise", "bridge", "eye of Sauron", "surpass / too much", "bone", "slippery", "Sparkles", 
"ratio", "bitter flavor", "enjoy", "medicine", "omen", "escape", "leap up", "look at for a long time while lost in thought", "challenge", 
"peach", "brush/fork", "write", "regulation", "action/ incident", "paintbrush", "suddenly", "sugar", "arrest", "health", "discard", 
"buddy", "flock", "wife", "deeyammn / hella", "battle", "quiet", "double-duty", "eww!!", "modesty", "build", "healthy", "prolong", 
"birthday / birth", "garden", "shish kebab", "coin", "shallow", "remain behind", "UFO", "listen to", "break", "nostalgia", "virtue", 
"tiger", "play", "consideration", "empty", "oppress", "epidermis", "lie", "lame", "sink", "get a job, you bum!", "kick", "pine cone", 
"engrave", "nucleus", "correspond to", "cough", "this", "shoddy", "lawn", "that", "flag", "basis", "period of time", "dupe", "enormous", 
"perception", "tolerate", "fang", "heresy", "already", "elegant", "general concept", "deplore", "bent dagger", "epitome", "dull", 
"opposite", "compared to", "resemble", "to be told / consent", "humid", "FFFFFoolio", "step / stairs", "interest", "free time", 
"ancient Chinese dragon", "onslaught", "ku klux klan", "patrol", "disaster", "Wu dynasty of China", "mistake", "entertainment", "melon", 
"isolation", "arc", "deed", "fake", "fusion", "segregate", "robust", "worship", "reciprocal", "gorgeous", "katakana 'ku'", "katakana 'me'", 
"katakana 'ra'", "katakana 'ho'", "katakana 'te'", "katakana 'o'", "katakana 'no'","???","dot", "katakana 'yu' radical" ];

let kanji_character = [
"一", "二", "三", "了", "子", "女", "好", "姦", "口", "品", "言", "下", "不", "否", "十", "古", "叶", "計", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/heel-49c0a317d54538e5d4ac0af5deacba71956eaed466cdea1f303aa5701c360260.jpg'>", 
"七", "比", "叱", "日", "旨", "昆", "唱", "晶", "旧", "早", "旦", "白", "皆", "水", "泉", "氷", "永", "泳", "泊", "汁", "混", "月", "湖", "明", "脂", "胆", 
"朝", "火", "炎", "淡", "談", "丁", "灯", "可", "河", "訂", "田", "町", "畑", "胃", "入", "人", "何", "信", "化", "花", "苦", "草", "荷", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/inside-f03d05519e12458d78b59efde245250129169f4097d925d7af07664ba18a3422.jpg'>", 
"内", "肉", "円", "市", "肺", "姉", "目", "冒", "帽", "自", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/lid-74fd4d023014470d11e02b9eaaebf92be5ce5248ea928e330815c4e740521e29.jpg'>", 
"亭", "停", "卒", "方", "万", "訪", "妨", "肪", "又", "双", "奴", "文", "斉", "済", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/4-7ed703e566cf97d54436a490d7c6024175b5a2f301072fa9e797488cfe4affce.jpg'>", 
"収", "叫", "心", "必", "怒", "息", "思", "L", "亡", "忙", "忘", "盲", "妄", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/net-0e8e17740ecf349f5de7ed6d27ac01cc5c8c1f94a4dc28aa5c65e04d708f447c.jpg'>", 
"慢", "漫", "亜", "悪", "夕", "多", "夢", "夜", "液", "名", "死", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/fortunetellin-6527ad92c2845b33cf04fe0b114516389a9cce89c1f1258a9577ba4823d432a3.jpg'>", 
"外", "上", "卓", "占", "点", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/crown-bbb43f3982d7790e8129074eea0d210c08b9ae58d15ef0ea7dbc05744779ce08.jpg'>", 
"宅", "安", "字", "宣", "喧", "八", "穴", "六", "沿", "ム", "公", "訟", "台", "治", "始", "怠", "能", "熊", "態", "仏", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/horny-bean-367e96f7f8c0f07b0a41c89a9941b2d39ff982570ff9d8703887652e7bfa6349.jpg'>", 
"立", "辛", "幸", "宰", "泣", "位", "音", "章", "暗", "意", "億", "憶", "門", "闇", "間", "問", "刀", "前", "切", "召", "昭", "照", "分", "剤", "罰", 
"刃", "忍", "認", "力", "加", "協", "脅", "努", "男", "九", "究", "丸", "熟", "執", "小", "少", "劣", "妙", "省", "京", "涼", "景", "示", "宗", "寂", 
"督", "<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/young-a3b4e8df7c3a2b71daf53d3039de5247a6f628574a9a7dfa598114470a1c1b3e.jpg'>", 
"幼", "玄", "畜", "蓄", "糸", "紹", "線", "綿", "細", "総", "索", "納", "紛", "絹", "系", "孫", "係", "干", "刊", "用", "肝", "芋", "汗", "宇", "千", 
"舌", "話", "活", "辞", "憩", "半", "判", "伴", "平", "評", "呼", "土", "里", "量", "黒", "童", "憧", "埋", "坊", "吐", "塾", "士", "仕", "志", "吉", 
"詰", "結", "誌", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/dizzy-cac8f7fcc19378e40705516e2202e521af656f4b13a5e5e4bf8a08d4533772ba.jpg'>", 
"老", "孝", "者", "著", "緒", "諸", "署", "暑", "煮", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/turkey-c570e2806bec90b04d76c1509aa47af2d36d6515382c7e8cef9c4e75c2dbc454.jpg'>", 
"焦", "無", "維", "唯", "誰", "準", "護", "馬", "止", "雌", "肯", "歩", "渉", "紫", "足", "促", "踏", "正", "是", "定", "証", "歪", "走", "超", "尺", 
"駅", "昼", "訳", "沢", "手", "択", "推", "描", "提", "払", "批", "指", "打", "招", "拐", "担", "接", "拍", "挿", "看", "耳", "取", "最", "撮", "趣", 
"恥", "聞", "斤", "折", "丘", "哲", "誓", "訴", "竹", "筋", "簡", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/bamboo-key-b40e78c53b3336f9cf18bbedf57e4c1e25f6613a5e66498380eadf244939d36f.jpg'>", 
"作", "昨", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/moving-6c661ec1e8648112143a8e7d7e2021693d166f7775040a22612014b129f82fbb.jpg'>", 
"近", "辺", "迫", "込", "達", "進", "述", "木", "林", "森", "本", "体", "休", "枠", "析", "策", "刺", "新", "集", "棚", "松", "枯", "相", "箱", "想", 
"禁", "果", "課", "菓", "東", "練", "案", "杯", "膝", "保", "繰", "操", "染", "雑", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/wheat-5c10238911c756f95569a39bc86184e3f08246b959af46f84bbb342305bedff0.jpg'>", 
"稚", "和", "秘", "私", "秒", "移", "利", "季", "委", "香", "秋", "愁", "末", "未", "妹", "味", "米", "迷", "謎", "断", "継", "粘", "粋", "粒", "粉", 
"来", "番", "審", "大", "奥", "奇", "寄", "臭", "奮", "器", "突", "央", "映", "英", "犬", "伏", "黙", "然", "燃", "太", "駄", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/kanji-no-kan-5fc45c2561c2d627790a493a80daf8d66f82033826d03cfb07a7de961fa1c267.jpg'>", 
"漢", "難", "勤", "嘆", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/opium-2198ee3f46f813acd0a0a0c1a39ba2bb998f42bb2adda96c74671bd2fa949dbf.jpg'>", 
"模", "墓", "暮", "募", "幕", "漠", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/box-fd9c4e52deb13621e0f25979fa9e5bb02bb5277d9c217368d66c68d0d83eaeec.jpg'>", 
"因", "恩", "菌", "困", "囚", "回", "固", "個", "井", "囲", "丼", "王", "玉", "国", "宝", "理", "任", "妊", "皇", "望", "聖", "程", "主", "契", "喫", 
"潔", "注", "柱", "住", "駐", "害", "割", "素", "憲", "青", "請", "清", "精", "晴", "情", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/rifle-afc6c7cade15033b575cba349e8efd636f1ee165ed09a2eac79fd2e5609f8c86.jpg'>", 
"生", "星", "性", "姓", "朱", "株", "遊", "称", "乙", "乾", "母", "毒", "毎", "梅", "海", "悔", "侮", "中", "忠", "患", "仲", "虫", "蛇", "蚊", "騒", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/corpse-db758d49e1dfb9468c0650fecfb4d188b6aa9efc04a4cbb1f2b4a69ea9a3fa3d.jpg'>", 
"属", "居", "尼", "泥", "尿", "尻", "刷", "戸", "所", "肩", "雇", "房", "戻", "涙", "毛", "尾", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/bunnyears-9f089fd2e097c62527101b50bfb19a4d56d327386249574d4c524453d0a9820b.jpg'>", 
"革", "靴", "甘", "某", "謀", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/legshuman-5748f0d35c379ff1f8a37b0f89a28c3d9c6ff0a3394da2258bfb1c029937b33b.jpg'>", 
"見", "寛", "焼", "境", "現", "親", "兄", "克", "況", "競", "児", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/legsanimal-cd3f1847e790bad8a84da19d15c29d5217e703c4cae46b62552dbf55e8f1ea2a.jpg'>", 
"貝", "買", "憤", "噴", "貨", "貧", "貯", "賭", "質", "賃", "貞", "偵", "員", "損", "則", "側", "測", "貫", "慣", "責", "績", "積", "貴", "遺", "兵", 
"浜", "<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/fishhook-4f2a537ef7bb6321381b62f920f62f0ec3e6523098d2f9f94056b407b4eef34a.jpg'>", 
"負", "魚", "角", "触", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/pi-d0cb96868438727e26d83f3ab791d83fa376b82122a7186e431389a03340de0c.jpg'>", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/fatpie-d96a7f3a07b501f0e0af640ec16ae093c66fccacc9674d1e75a19573608255dc.jpg'>", 
"売", "続", "読", "窓", "探", "深", "具", "元", "完", "西", "票", "標", "漂", "酒", "酔", "価", "要", "腰", "煙", "才", "財", "材", "閉", "夫", "賛", 
"替", "潜", "規", "挟", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hay-e79dca9c4c48cea0fcd662f62784cf7665c6305bf7aa7448d1a1039aa0328683.jpg'>", 
"巣", "光", "単", "桜", "肖", "削", "消", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/nest-c615192568fa8f2d0d4674ab27de4c1d86bf78524f9d8828a42ce9a510971982.jpg'>", 
"菜", "浮", "受", "妥", "授", "採", "久", "各", "愛", "客", "落", "格", "絡", "略", "路", "条", "麦", "酸", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/grab-f336bd5ae2c6e96b790d3c393ad77d3f028d3b822eb6402d73804c61945a9117.jpg'>", 
"秀", "誘", "透", "携", "及", "吸", "級", "扱", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/snout-0da95d6967159c3df9fac5ca65e0c174d9134efc4fc7ddc9773c43687db1590e.jpg'>", 
"穏", "侵", "浸", "緑", "急", "当", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/swordswallower-bc9c70473e72ba6a70c104d811e8931f3684e7d730440f4bc8a7ac392b7b26e0.jpg'>", 
"婦", "掃", "帰", "帝", "締", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/mutant-28446577e00af4abd5ee28432ac3a925a6924f83b3ae485e2b88d29e40207672.jpg'>", 
"躍", "濯", "曜", "工", "空", "控", "紅", "功", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/capn-hook-55b108befbd1170c27ab1fca98cd3c7f942eae6c607da41e5d04bfefc2a6d42b.jpg'>", 
"巧", "与", "写", "汚", "極", "誇", "号", "考", "拷", "式", "拭", "試", "武", "代", "貸", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/spearthree-1237d0259e43c07b511af51d7d4cd37e1f5a3af5c742c089bfde9e8b42c12b95.jpg'>", 
"閥", "惑", "我", "賊", "域", "戦", "栽", "幾", "機", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/sentry-e50d475041e7ca63af18b422f089c86b40ad6b1fcd7f2c145a1dd49bc4c7cde1.jpg'>", 
"職", "織", "識",
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/container-f9b73d808a6be6931ecb146a939eb00daada8927f177cfe6f054dd7f39297589.jpg'>", 
"区", "駆", "巨", "拒", "距", "臣", "堅", "緊", "賢", "覧", "臨", "姫", "匹", "匠", "四", "喚", "換", "欠", "欧", "歌", "吹", "炊", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/taskmaster-a9622749e58c326a1186be084254423921b1cc8ca16d3c2bd585cd3432e3d861.jpg'>", 
"数", "枚", "敏", "敗", "故", "政", "放", "教", "激", "繁", "攻", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/yosemite-sam-2997d96373541ff15b06620288fd09f36438449995bb9127f049b46482f67f43.jpg'>", 
"敵", "適", "滴", "摘", "己", "改", "起", "紀", "記", "配", "求", "救", "球", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/cliff-eb964a7a38cc1eda9e77d53b06bbf667cf8e51ab57d85230e8646cb368f49521.jpg'>", 
"厳", "励", "歴", "厚", "圧", "粧", "備", "灰", "産", "原", "源", "反", "返", "坂", "板", "仮", "販", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/open-scissors-1adae64d04c7b1237b3933730ca28c5a7aac472ca1fbf4eb4a1162aae968b0b8.jpg'>", 
"成", "誠", "越", "蔵", "臓", "歳", "滅", "威", "城", "幻", "気", "決", "快", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hitler-4b76f0c76d4d8ea085e1e6cda3b7d25841272f4fad56777afc29dd5daa0ced51.jpg'>", 
"獣", "減", "感", "憾", "同", "筒", "司", "伺", "詞", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/faction-ee6efa78c42a24bb74e100922ec74a34af1b5cfae8ec1dd235aab8a78ef2a83c.jpg'>", 
"旅", "派", "脈", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/far-6e5a6d9f07b7e286cb081a537cd4b5927b3eaf2e9c5769ca62059e4fe649a5a1.jpg'>", 
"遠", "園", "環", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/kickinthenuts-8d1df2f5e6c8ce81eee9dd2921dc896fc82951953d4d3f8c8851bafe19d28bc5.jpg'>", 
"表", "衣", "依", "袋", "裁", "褒", "裏", "哀", "衰", "良", "娘", "退", "浪", "眼", "恨", "根", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/town-db7daa05a3fc4ec8fa825748b5a4251143f7e7898c371e942a475cc3afb11fb1.jpg'>", 
"限", "郷", "響", "階", "障", "院", "防", "陥", "都", "隠", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/amount-302e93974444b88ecaf78271488f5127b984e7f8d501c6aa6117cce7e15c93dc.jpg'>", 
"部", "剖", "倍", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/twodicks-a3c40a59be6c297d73552a1c44f022079ac62973a04a564f931913afb1cdf7eb.jpg'>", 
"壮", "装", "状", "寝", "北", "背", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hurl-3fc04bdc7d9e68d051ac2eb09ed076ea006951a06a4c2eb1901e82d86fd2c0a4.jpg'>", 
"制", "製", "告", "造", "酷", "先", "洗", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/terrorist-a97e918ac28a3c3e4eae67b2cf62c9513cba9baf0241033b39ad6d9ae091a536.jpg'>", 
"面", "百", "憂", "優", "宿", "縮", "石", "砂", "砕", "礎", "山", "岩", "帯", "滞", "催", "崩", "密", "幽", "岸", "炭", "岳", "鳥", "島", "鳴", "豆", "喜", "嬉", "頭", "夏", "願", "頑", "頃", "頂", "額", "類", "題", "顧", "傾", "項", "川", "順", "州", "訓", "荒", "慌", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/horny-5d69a650381661337deb271d6458f0daf77b2f7c8dec8dccaa69dbe72baced67.jpg'>", 
"首", "道", "税", "説", "脱", "磁", "羊", "￥", "南", "美", "鮮", "詳", "洋", "遅", "着", "養", "義", "儀", "議", "様", "天", "添", "笑", "呑", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/horny-heaven-1c23a31ba8e70492c7c7585412d83c8d1a60390319dfef9339288d2537d7354f.jpg'>", 
"送", "咲", "関", "巻", "圏", "券", "勝", "弓", "弟", "第", "沸", "費", "強", "引", "弾", "赤", "湾", "跡", "恋", "変", "長", "張", "帳", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/peaked-roof-4dff88cad33f30f1612441068929e332090931266ad2e7895663210f711c2b0f.jpg'>",
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/risk-72bcf8103577ba53a33af648a808df633422429f9145158ee2668a15d9a10a8e.jpg'>", 
"険", "検", "倹", "剣", "験", "金", "鋭", "錆", "録", "鏡", "鎖", "銀", "針", "銅", "茶", "傘", "全", "企", "食", "飲", "飾", "飯", "飼", "幹", "舎", "捨", "余", "塗", "途", "除", "倉", "創", "介", "界", "合", "給", "塔", "拾", "搭", "答", "ラ", "今", "含", "念", "令", "鈴", "領", "命", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/frost-5ec89fbe973c4a148303e4e50bc5f1f40bb4f0dd078b3abab9a949dfc3c9c620.jpg'>", 
"冷", "凍", "尽", "冬", "終", "次", "姿", "資", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/3-stooges-f6130bf7251120fb97cf6ba893322c45f9c5cc7990a439b8e4e060bf45604273.jpg'>", 
"寒", "奏", "春", "棒", "実", "冊", "扁", "編", "騙", "偏", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/barbershop-ddcfd6e4ae9fdbe08541fbc47911294254242cfbd8fb5dd5a97dae8d8f44181e.jpg'>", 
"論", "倫", "寸", "付", "附", "討", "奪", "守", "団", "符", "村", "寿", "慰", "尋", "導", "闘", "寺", "詩", "時", "持", "侍", "等", "尊", "噂", "父", "交", "対", "校", "郊", "効", "絞", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/tntplunger-01f67fb0507f284ca93fe094973e62dcb76f85c6d57259b14d3ab4da96ec7de0.jpg'>", 
"専", "博", "縛", "薄", "演", "恵", "敷", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/pit-4d2f057ef66ff7acfceb67d578be507b3de8a752405dbda9173cc63c791a2676.jpg'>", 
"画", "両", "満", "出", "屈", "掘", "缶", "揺", "世", "葉", "喋", "歯", "噛", "齢", "凶", "脳", "悩", "離", "矢", "疑", "擬", "短", "医", "族", "候", "知", "失", "鉄", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/swan-dc9bb421ad16fca421f77d6dc9e4a631822028274d02498ec547659ccde97bce.jpg'>", 
"観", "勧", "権", "確", "車", "重", "垂", "乗", "陣", "輪", "軒", "較", "軟", "載", "軍", "揮", "連", "運", "輝", "華", "睡", "郵", "剰", "種", "動", "働", "腫", "非", "輩", "悲", "罪", "俳", "排", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/takedump-fb2fb33ad14b25c1d1fe12aa761d9e77d2315e00db86e53caa9f46793e30fd2f.jpg'>", 
"軽", "経", "怪", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/naruto-57c1b7af72b9c81fad4e9a17de7a6136df0529b8b9dc47fb7cdb13cddcd0df22.jpg'>", 
"友", "抜", "雄", "布", "希", "怖", "右", "左", "若", "有", "堕", "賄", "差", "在", "存", "片", "版", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/crows-d312a1500ced69aed1e944e99b93f96ce7649d411356f44d741f04018b503329.jpg'>", 
"暖", "援", "緩", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hair-d41d8f27d97bb53437823f2b479fd601cf1a274c929adf9196a9fc20d6b68bd6.jpg'>", 
"髪", "彩", "影", "顔", "参", "修", "惨", "膨", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/salon-40a4f5ab52a899ec55975140a8d3f613971dbd7db0dc89a60ce1cec2bb979e2e.jpg'>", 
"珍", "診", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/cave-60f54a97d951c286ffb24de144dc19bc1ce77890008fbb4491094a71d464a2e6.jpg'>", 
"廊", "磨", "腐", "応", "府", "庁", "庫", "店", "座", "床", "麻", "摩", "広", "拡", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/mole-722ba85b4b5feb5d8c20b2c75967fcf9c206ad68dc5879bccc9320e0d8d65d20.jpg'>", 
"庶", "席", "度", "渡", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/villain-06f762a0e6912403f9e1744e2d15f0b012cf851ee91556e6feb744b6f0385f53.jpg'>", 
"鬼", "魔", "魅", "醜", "塊", "卑", "氏", "底", "紙", "低", "婚", "抵", "民", "眠", "曲", "豊", "典", "遭", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/payback-66dfafac87810e3d8a87ed5e8294a1752a622ff197275a59230b5b472ab11438.jpg'>", 
"農", "濃", "辱", "娠", "振", "唇", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/TEEPEE-33e84d5f2415b081c6f9a5cbe48a37a1511a4d1eea033f1fce6a13cd26b90cda.jpg'>", 
"登", "祭", "際", "察", "擦", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/open-22a4efb0f9e03966fd5f53babc15713162215fece5c4cfe63bc00f7fa65c5c45.jpg'>", 
"開", "発", "廃", "形", "研", "刑", "型", "午", "許", "牛", "件", "特", "牲", "犠", "解", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/thing-c191cf0af6d70aa6ad9fad73f8c34fde1d6e14f507e23a3a4cb6f1e43da4454b.jpg'>", 
"物", "惚", "易", "湯", "揚", "陽", "傷", "場", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/worm-on-the-end-of-a-hook-9b6c21d6a38309280e30170389fe7f83772e398a289b5a08615db768d9f74447.jpg'>", 
"色", "免", "逸", "晩", "絶", "勉", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/lorgnette-d44a21af48ff94983ac03c88ed433d20045a08e8b02d7ad46270f458254e8692.jpg'>", 
"声", "肥", "豚", "象", "像", "縁", "家", "嫁", "稼", "遂", "隊", "行", "徐", "徒", "径", "後", "往", "待", "得", "従", "縦", "術", "衝", "微", "徴", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/order-rule-f81bf6e19f39cc1dd21afd3385f9141dcb7c41215f6eb8adc9ac36cc2058231a.jpg'>", 
"育", "徹", "撤", "流", "陰", "充", "銃", "統", "至", "到", "致", "倒", "去", "法", "怯", "屋", "室", "握", "貿", "留", "云", "転", "伝", "魂", "芸", "会", "絵", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/termite-mound-b78ecd66ff1ae83574b92d4cb7b88fb3d1c7e096dad438fda98ceeda558ee9b3.jpg'>", 
"街", "掛", "涯", "封", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/pie-shop-a683edf1bab8f01e394d14359d264ca8d65b3a12041a64ebdf9439e76ee12ef1.jpg'>", 
"陸", "勢", "熱", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/diaper-87d0493e561c441f9fd882c0b44408e91bb3026ef8de3306334a9fdb977faea9.jpg'>", 
"冗", "肌", "抗", "机", "風", "飢", "処", "拠", "凡", "築", "恐", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/throw-e74211194ac15d8015b5c277e8c74c77a5498681b905740de79c366b5ab7a5d9.jpg'>", 
"投", "役", "設", "没", "殺", "殴", "股", "撃", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/ten-eyes-1e69ba5f864a95c1c595487687a509a73e10994493e1f63d6267a8affe204c43.jpg'>", 
"盾", "循", "真", "慎", "県", "懸", "直", "置", "値", "植", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/ssshhhh-27e71c34ffc03caec4c706350ebedac091e4166219973ca447bbc1e689d588db.jpg'>", 
"殖", "別", "列", "裂", "烈", "例", "支", "皮", "彼", "枝", "技", "鼓", "破", "波", "マ", "勇", "予", "序", "預", "野", "矛", "柔", "務", "束", "疎", "頼", "速", "整", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/PASS-e6cfef3ebdc757da9e6ff346a04a18567ecc60b4baea2adebea839a5da3aa230.jpg'>", 
"通", "踊", "丙", "柄", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/sickness-7e5db75dc0667ed9131429e9612fa8602f14a94acff4f0888cd75fab2d5a1483.jpg'>", 
"病", "痛", "疲", "痢", "痴", "症", "痺", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/butcher-8bfe9c87df1ad0ef844dc596b8d836c8bd383bfdb7b4c75f97a87d836c02e439.jpg'>", 
"癒", "愉", "諭", "輸", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/STINKY-a2937a02f7d42cfb23d0c265791b68ffe2d56a48bb7bd50d5af4bc2319436746.jpg'>", 
"癖", "避", "壁", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/big-small-horny-sun-cefd0c80c057ef1b9117fe801fcadb29f17a4b0ca54d9c16ca8d954e4fcb772b.jpg'>", 
"療", "寮", "僚", "申", "痩", "紳", "捜", "伸", "甲", "押", "由", "抽", "宙", "油", "届", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/TURTLE-SOUP-be2b8cc86f923bb2d4fa7c65fdeee64d4fd1c89d8a9039266f14a484e8942cdc.jpg'>", 
"偶", "隅", "愚", "雨", "霧", "雲", "曇", "霜", "雷", "震", "漏", "雪", "雰", "露", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hedgehog-b5cf7f3d60c4916a3a8d255da849c9261ad972bae34000afa0baaca35cd88f68.jpg'>", 
"霊", "湿", "業", "僕", "撲", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/dragon-0ebdc05bfc5929a3cf8da0b22f3924ea3252fc6758ae9c7eee03495eb97c0c2f.jpg'>", 
"竜", "滝", "電", "俺", "亀", "縄", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/comb-96aa9c4894b742554981021dd40472c983d4e77e37e1413573dad646066cd9d7.jpg'>", 
"需", "耐", "端", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/wrap-8b605498eb7fbb8fcb122bce09c2238485eab76321ebea6535d4a35fb962c117.jpg'>", 
"包", "胞", "泡", "砲", "飽", "抱", "胸", "句", "敬", "警", "驚", "局", "拘", "旬", "陶", "匂", "渇", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/promise-112f5d82ff01e012d3b059eb6b867d9194690dffa3a560b54ab130db89ad2620.jpg'>", 
"約", "的", "釣", "均", "皿", "盗", "温", "盟", "盛", "塩", "監", "鑑", "血", "衆", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/crab-079aa7116919ec1031e2feaaa111df5f33753e70d8a57632c6e44bf52629d7c5.jpg'>", 
"益", "溢", "誉", "挙", "舟", "船", "航", "般", "盤", "猫", "猛", "猥", "猿", "狩", "狂", "独", "獄", "獲", "狭", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/fingerprint-c8cfbed512b04469635b834e2dbed4a48e8a8b35c141e0c85d23a38fce87c772.jpg'>", 
"犯", "印", "叩", "卵", "却", "範", "御", "腕", "即", "節", "厄", "危", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/clown-possee-32ccfb40811f22406538cff3ee9d548f7fe65ec4f8fc04cb3aae7ec1a0ac6e2e.jpg'>", 
"抑", "迎", "仰", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/clothes-21bbc995543c98ff39397a573766fb5c02f5c937a849e6ec1bc3f6944dd173ed.jpg'>", 
"服", "報", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/abelincolnshat-15c33877affbc42e181274a0a78fe029e7e0ef7b8fb2d7cec4e56a44417be949.jpg'>", 
"狙", "組", "阻", "粗", "査", "畳", "助", "ネ", "祖", "視", "祝", "社", "祈", "祉", "神", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/wine-bottle-326a630e521ebaa33b144ad5eb73e00f177f587df5f3151d71dc99b119e705f0.jpg'>", 
"福", "副", "幅", "富", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hook-6fd959c7d2b1bafb1ca6d92adf8e7e655af2880899b2d7cef45d56984c51832f.jpg'>", 
"礼", "乱", "札", "乳", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/clothing-ee85f4b3017dd097516dba1d2d258d024cd3202308c5882b64508f56f033fee7.jpg'>", 
"初", "裸", "被", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/dork-9bd6753922ee078ae63418f092889784721154cb923681d1d17a3b545b27d44a.jpg'>", 
"複", "腹", "復", "履", "谷", "裕", "欲", "俗", "容", "溶", "浴", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hell-bddafdb6d661ddc95918f0953bb6d719438e7f1c24ce7f6aa160124c4069832e.jpg'>", 
"鼻", "葬", "算", "弁", "昇", "戒", "械", "羽", "飛", "翌", "習", "弱", "扇", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/devilbunny-416764d4ed675a25bb5736dbbdbdaf6dae2e9a72489820ef71b7c68341c5e1ea.jpg'>", 
"散", "展", "譲", "昔", "借", "惜", "籍", "黄", "嬢", "横", "共", "並", "普", "供", "選", "洪", "巷", "港", "異", "翼", "暴", "爆", "再", "甫", "舗", "補", "捕", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/hells-circus-f3170dde0a8d6b6096566715ba21cbe03f77358165a411572318aaf6e4e3289e.jpg'>", 
"構", "講", "購", "溝", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/fuckkk-fdac0d1870aaf431c52baf171ec20851da74efe28744ae0ffc046a25ee84e725.jpg'>", 
"降", "年", "五", "語", "悟", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/orgy-b66a4017e2961ce98db535e0b3456766c108f0e1a3ea272d031a95290a6e43ef.jpg'>", 
"違", "偉", "衛", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/date-9ccd648988a49078c8c081be775a502a55077433edc6e2c1fe015d45a401c38d.jpg'>", 
"瞬", "舞", "隣", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/spice-rack-b87f6abc3e3cc4b36865f213079b66b2a6a785d3e1825833e55112fd3776a627.jpg'>", 
"料", "科", "図", "斜", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/skipping-legs-0b022a425912c37a28e6ae08efaba729e7a0483fa75e15cf2d833e50ed469766.jpg'>", 
"史", "更", "硬", "使", "便", "身", "射", "謝", "窮", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/scorpion-f906743e5aec2f4460b4d73b30c553ff20a4c773d405a2388a840c3433506ac0.jpg'>", 
"地", "池", "他", "施", "曽", "増", "贈", "憎", "僧", "層", "呂", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/beuracracy-3a90b71be341428c01da9c5346a976af0d429b2f55e61d9fc1e6c7b230a9e43b.jpg'>", 
"宮", "官", "館", "棺", "追", "遣", "管", "師", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/mohawk-13aca159f6a6b70e0a5feaf0abcefe5426e4fce812d81e90c54a4870cac986d4.jpg'>", 
"営", "労", "栄", "学", "覚", "党", "尚", "賞", "償", "常", "堂", "善", "繕", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/goatee-f0f4a557d7228e465bc222e736747441dd80e27b57ab376c416df57b0a25624a.jpg'>", 
"周", "調", "週", "彫", "高", "豪", "向", "商", "橋", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/sauron-b83950de37356253dacb44c0cffac58aad03199732e1c1fe95d198d377c6fc08.jpg'>", 
"過", "骨", "滑", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/sparkle-b7cd3ce260e7974ab2587cd5ed3aa30f56661e39c2f4d020e2252320a5293c37.jpg'>", 
"率", "渋", "楽", "薬", "兆", "逃", "跳", "眺", "挑", "桃", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/brush-84be58bf93ab2e1e14c78a3ea5b087d071cc780b644b5aa13c9f7816663343be.jpg'>", 
"書", "律", "事", "筆", "唐", "糖", "逮", "康", "棄", "君", "群", "妻", "凄", "争", "静", "兼", "嫌", "謙", "建", "健", "延", "誕", "庭", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/shishkebab-5b4f6b60cdbe123e7d1be4f97bacdaf70bb9e3555f8144adfabab6b96dc1ef5e.jpg'>", 
"銭", "浅", "残", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/ufo-598fa53db0efa1c1212dbfdb7cba400591bae7cdf22bcb73188cfd443a05be54.jpg'>", 
"聴", "壊", "懐", "徳", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/tiger-473ea961d101d552466c791abd56e6812d324e792abdfde094c94f23cdf70dc7.jpg'>", 
"劇", "慮", "虚", "虐", "膚", "嘘", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/lame-6c6e525bc6248b073dd7ae90653c3c3eac7927325a411fff22126d386610f278.jpg'>", 
"沈", "就", "蹴", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/pine-cone-390f89731b41aee8d0a5047615ccbb1875e1be4eb13e5ecad13e433639263e80.jpg'>", 
"刻", "核", "該", "咳", "之", "乏", "芝", "其", "旗", "基", "期", "欺", "甚", "勘", "堪", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/fang-657c344b1343945391f6b943f374d6b118269962168a4cff490a1be641133a27.jpg'>", 
"邪", "既", "雅", "概", "慨", "屯", "純", "鈍", "逆", "以", "似", "承", "蒸", 
"<img class='k_char' src='https://www.kanjidamage.com/assets/radREALLYsmall/foolio-42347b0e4934b9f5e3d531a1722a0647aede8766ea45074316dbd4f6d5f784f2.jpg'>", 
"段", "興", "暇", "龍", "襲", "&lt;&lt;&lt;", "巡", "災", "呉", "誤", "娯", "瓜", "孤", "弧", "為", "偽", "融", "隔", "丈", "拝", "互", "麗", "ク", "メ", "ラ", "ホ", "テ", "オ", "ノ","???","丶", "ユ" 

];